apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: interlogica-be
          image: giusetega/interlogica:latest
          ports:
            - containerPort: 8080
#          command: ["sh", "-c", "cp -r /seed-images/* /app/static/tmp/ || true"]
          volumeMounts:
            - name: interlogica-volume
              mountPath: /app/static/tmp

      volumes:
        - name: interlogica-volume
          persistentVolumeClaim:
            claimName: interlogica-pvc