apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interlogica-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: local-storage
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
