apiVersion: v1
kind: PersistentVolume
metadata:
  name: interlogica-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
  storageClassName: manual
  local:
    path: /mnt/disks/ssd1