apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

nameSuffix: -prod

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
#  - path: patch-ingress.yaml

#images:
#  - name: giusetega/interlogica
#    newName: ghcr.io/giusetega/interlogica
#    newTag: latest
