name: Interlogica CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify -B

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-jar
          path: target/*.jar

  sonar:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: ./.github/actions/sonar
        with:
          project_key: giusetega_interlogica
          organization: giusetega
          sonar_token: ${{ secrets.SONAR_CLOUD_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: SonarCloud Scan
#        run: >
#          mvn verify -B sonar:sonar
#          -Dsonar.projectKey=giusetega_interlogica
#          -Dsonar.organization=giusetega
#          -Dsonar.host.url=https://sonarcloud.io
#          -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}
#
#      - name: Print Quality Gate & New Code Coverage
#        run: |
#          PROJECT_KEY="giusetega_interlogica"
#          SONAR_API="https://sonarcloud.io/api"
#
#          echo "Fetching Quality Gate status..."
#          QG_STATUS=$(curl -s -u ${{ secrets.SONAR_CLOUD_TOKEN }}: \
#            "$SONAR_API/qualitygates/project_status?projectKey=$PROJECT_KEY" \
#            | jq -r '.projectStatus.status')
#
#          NEW_COVERAGE=$(curl -s -u ${{ secrets.SONAR_CLOUD_TOKEN }}: \
#            "$SONAR_API/measures/component?component=$PROJECT_KEY&metricKeys=new_coverage" \
#            | jq -r '.component.measures[0].value')
#
#          echo ""
#          echo "Quality Gate: $QG_STATUS"
#          echo "New Code Coverage: ${NEW_COVERAGE}% (threshold 80%)"

#      - name: SonarCloud Quality Gate
#        uses: sonarsource/sonarqube-quality-gate-action@v1
#        timeout-minutes: 5
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    env:
      DOCKER_TAG: ${{ vars.DOCKERHUB_USERNAME }}/interlogica:${{ github.sha }}
      DOCKER_TAG_GHCR: ghcr.io/${{ github.repository_owner }}/interlogica:${{ github.sha }}
    steps:
      - uses: actions/checkout@v5

      - name: Download jar
        uses: actions/download-artifact@v5
        with:
          name: app-jar
          path: target

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - uses: docker/setup-buildx-action@v3

      - name: Build docker tag and push
        run: |
          echo "Packing application to registry..."
          docker buildx build -t ${{ env.DOCKER_TAG }} -t ${{ env.DOCKER_TAG_GHCR }} --push .