name: Interlogica CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify -B

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=giusetega_interlogica \
          -Dsonar.organization=giusetega \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}

      - name: List folder
        run: ls && ls target

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker:
    name: Containerization
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: app-jar

      - name: List folder
        run: ls && ls target

      - name: Build docker tag
        run: |
          echo "Packing application to registry..."
          docker buildx build -t interlogica:${{ github.sha }} .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker tag
        run: |
          echo "Pushing to github..."
          docker push interlogica:${{ github.sha }}