name: Interlogica CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify -B

#      - name: SonarCloud Scan
#        run: >
#          mvn -B sonar:sonar
#          -Dsonar.projectKey=giusetega_interlogica
#          -Dsonar.organization=giusetega
#          -Dsonar.host.url=https://sonarcloud.io
#          -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-jar
          path: target/*.jar

  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: SonarCloud Scan
        run: >
          mvn -B sonar:sonar
          -Dsonar.projectKey=giusetega_interlogica
          -Dsonar.organization=giusetega
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
#        run: mvn -B sonar:sonar


  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    env:
      DOCKER_TAG: ${{ vars.DOCKERHUB_USERNAME }}/interlogica:${{ github.sha }}
      DOCKER_TAG_GHCR: ghcr.io/${{ github.repository_owner }}/interlogica:${{ github.sha }}
    steps:
      - uses: actions/checkout@v5

      - name: Download jar
        uses: actions/download-artifact@v5
        with:
          name: app-jar
          path: target

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - uses: docker/setup-buildx-action@v3

      - name: Build docker tag and push
        run: |
          echo "Packing application to registry..."
          docker buildx build -t ${{ env.DOCKER_TAG }} -t ${{ env.DOCKER_TAG_GHCR }} --push .


#      - name: Push docker tag to docker hub and ghcr
#        run: |
#          echo "Pushing to github..."
#          docker push ${{ env.DOCKER_TAG }}
#          docker push ${{ env.DOCKER_TAG_GHCR }}