name: Interlogica CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean verify -B

      - name: SonarCloud Scan
        run: >
          mvn -B sonar:sonar
          -Dsonar.projectKey=giusetega_interlogica
          -Dsonar.organization=giusetega
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-jar
          path: target/*.jar

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_TAG: ${{ vars.DOCKERHUB_USERNAME }}/interlogica:${{ github.sha }}
      DOCKER_TAG_GHCR: ghcr.io/${{ github.repository_owner }}/interlogica:${{ github.sha }}
    steps:
      - uses: actions/checkout@v5

      - name: Download jar
        uses: actions/download-artifact@v5
        with:
          name: app-jar
          path: target

      - name: Build docker tag
        run: |
          echo "Packing application to registry..."
          docker buildx build -t ${{ env.DOCKER_TAG }} .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR login
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker tag to docker hub and ghcr
        run: |
          echo "Pushing to github..." \
          docker push ${{ env.DOCKER_TAG }} \
          docker push ${{ DOCKER_TAG_GHCR }}